# Generated by Django 4.1 on 2022-08-27 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='datedcompleted',
            new_name='datecompleted',
        ),
    ]
