# Generated by Django 4.2.7 on 2023-12-26 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_comment_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
