# Generated by Django 4.2.7 on 2023-12-27 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_due_date_task_fecha_limite'),
        ('tasks', '0006_delete_comment'),
    ]

    operations = [
    ]
