# Generated by Django 4.2.7 on 2023-12-27 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_shared_task_shared_with'),
        ('tasks', '0007_merge_20231226_1934'),
    ]

    operations = [
    ]
