# Generated by Django 4.2.7 on 2023-12-27 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_merge_20231226_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='shared',
        ),
        migrations.RemoveField(
            model_name='task',
            name='shared_with',
        ),
    ]
